<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Operations;

use \Testing\petstore\Utils\SpeakeasyMetadata;
class DeletePetRequest
{
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=api_key')]
    public ?string $apiKey = null;
    
    /**
     * Pet id to delete
     * 
     * @var int $petId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=petId')]
    public int $petId;
    
	public function __construct()
	{
		$this->apiKey = null;
		$this->petId = 0;
	}
}
