<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Operations;

use \Testing\petstore\Utils\SpeakeasyMetadata;
class FindPetsByTagsRequest
{
    /**
     * Tags to filter by
     * 
     * @var ?array<string> $tags
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=tags')]
    public ?array $tags = null;
    
	public function __construct()
	{
		$this->tags = null;
	}
}
