<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Operations;


class FindPetsByStatusResponse
{
	
    public ?string $body = null;
    
	
    public string $contentType;
    
    /**
     * successful operation
     * 
     * @var ?array<\Testing\petstore\Models\Shared\Pet> $pets
     */
	
    public ?array $pets = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->body = null;
		$this->contentType = "";
		$this->pets = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
