<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Operations;

use \Testing\petstore\Utils\SpeakeasyMetadata;
class FindPetsByStatusRequest
{
    /**
     * Status values that need to be considered for filter
     * 
     * @var ?\Testing\petstore\Models\Operations\FindPetsByStatusStatus $status
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ?FindPetsByStatusStatus $status = null;
    
	public function __construct()
	{
		$this->status = null;
	}
}
