<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Operations;

use \Testing\petstore\Utils\SpeakeasyMetadata;
class GetInventorySecurity
{
	#[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=header,name=api_key')]
    public string $apiKey;
    
	public function __construct()
	{
		$this->apiKey = "";
	}
}
