<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Operations;

use \Testing\petstore\Utils\SpeakeasyMetadata;
class GetOrderByIdRequest
{
    /**
     * ID of order that needs to be fetched
     * 
     * @var int $orderId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=orderId')]
    public int $orderId;
    
	public function __construct()
	{
		$this->orderId = 0;
	}
}
