<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Operations;

use \Testing\petstore\Utils\SpeakeasyMetadata;
class GetPetByIdRequest
{
    /**
     * ID of pet to return
     * 
     * @var int $petId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=petId')]
    public int $petId;
    
	public function __construct()
	{
		$this->petId = 0;
	}
}
