<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Operations;

use \Testing\petstore\Utils\SpeakeasyMetadata;
class GetPetByIdSecurity
{
	#[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=header,name=api_key')]
    public ?string $apiKey = null;
    
	#[SpeakeasyMetadata('security:scheme=true,type=oauth2,name=Authorization')]
    public ?string $petstoreAuth = null;
    
	public function __construct()
	{
		$this->apiKey = null;
		$this->petstoreAuth = null;
	}
}
