<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Operations;


class LoginUserResponse
{
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * successful operation
     * 
     * @var ?string $loginUser200ApplicationJSONString
     */
	
    public ?string $loginUser200ApplicationJSONString = null;
    
    /**
     * successful operation
     * 
     * @var ?string $loginUser200ApplicationXMLString
     */
	
    public ?string $loginUser200ApplicationXMLString = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->loginUser200ApplicationJSONString = null;
		$this->loginUser200ApplicationXMLString = null;
	}
}
