<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Operations;

use \Testing\petstore\Utils\SpeakeasyMetadata;
class LoginUserRequest
{
    /**
     * The password for login in clear text
     * 
     * @var ?string $password
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=password')]
    public ?string $password = null;
    
    /**
     * The user name for login
     * 
     * @var ?string $username
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=username')]
    public ?string $username = null;
    
	public function __construct()
	{
		$this->password = null;
		$this->username = null;
	}
}
