<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Operations;

use \Testing\petstore\Utils\SpeakeasyMetadata;
class UpdateUserRawRequest
{
    /**
     * Update an existent user in the store
     * 
     * @var ?string $requestBody
     */
	#[SpeakeasyMetadata('request:mediaType=application/xml')]
    public ?string $requestBody = null;
    
    /**
     * name that need to be deleted
     * 
     * @var string $username
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=username')]
    public string $username;
    
	public function __construct()
	{
		$this->requestBody = null;
		$this->username = "";
	}
}
