<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Operations;

use \Testing\petstore\Utils\SpeakeasyMetadata;
class UpdateUserFormRequest
{
    /**
     * Update an existent user in the store
     * 
     * @var ?\Testing\petstore\Models\Shared\User $user
     */
	#[SpeakeasyMetadata('request:mediaType=application/x-www-form-urlencoded')]
    public ?\Testing\petstore\Models\Shared\User $user = null;
    
    /**
     * name that need to be deleted
     * 
     * @var string $username
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=username')]
    public string $username;
    
	public function __construct()
	{
		$this->user = null;
		$this->username = "";
	}
}
