<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Operations;


class UpdatePetRawResponse
{
	
    public ?string $body = null;
    
	
    public string $contentType;
    
    /**
     * Successful operation
     * 
     * @var ?\Testing\petstore\Models\Shared\Pet $pet
     */
	
    public ?\Testing\petstore\Models\Shared\Pet $pet = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->body = null;
		$this->contentType = "";
		$this->pet = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
