<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Operations;


class UploadFileResponse
{
    /**
     * successful operation
     * 
     * @var ?\Testing\petstore\Models\Shared\ApiResponse $apiResponse
     */
	
    public ?\Testing\petstore\Models\Shared\ApiResponse $apiResponse = null;
    
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->apiResponse = null;
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
