<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Operations;

use \Testing\petstore\Utils\SpeakeasyMetadata;
class UploadFileRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/octet-stream')]
    public ?string $requestBody = null;
    
    /**
     * Additional Metadata
     * 
     * @var ?string $additionalMetadata
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=additionalMetadata')]
    public ?string $additionalMetadata = null;
    
    /**
     * ID of pet to update
     * 
     * @var int $petId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=petId')]
    public int $petId;
    
	public function __construct()
	{
		$this->requestBody = null;
		$this->additionalMetadata = null;
		$this->petId = 0;
	}
}
