<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Shared;

use \Testing\petstore\Utils\SpeakeasyMetadata;
class Order
{
	#[\JMS\Serializer\Annotation\SerializedName('complete')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=complete')]
    public ?bool $complete = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=id')]
    public ?int $id = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('petId')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=petId')]
    public ?int $petId = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('quantity')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=quantity')]
    public ?int $quantity = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('shipDate')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=shipDate,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $shipDate = null;
    
    /**
     * Order Status
     * 
     * @var ?\Testing\petstore\Models\Shared\OrderStatus $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<Testing\petstore\Models\Shared\OrderStatus>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=status')]
    public ?OrderStatus $status = null;
    
	public function __construct()
	{
		$this->complete = null;
		$this->id = null;
		$this->petId = null;
		$this->quantity = null;
		$this->shipDate = null;
		$this->status = null;
	}
}
