<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Shared;


/** Order Status */
enum OrderStatus: string
{
    case PLACED = 'placed';
    case APPROVED = 'approved';
    case DELIVERED = 'delivered';
}
