<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore\Models\Shared;

use \Testing\petstore\Utils\SpeakeasyMetadata;
/**
 * Pet - Create a new pet in the store
 * 
 * @package Testing\petstore\Models\Shared
 * @access public
 */
class Pet
{
	#[\JMS\Serializer\Annotation\SerializedName('category')]
    #[\JMS\Serializer\Annotation\Type('Testing\petstore\Models\Shared\Category')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=category,json=true')]
    public ?Category $category = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=id')]
    public ?int $id = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[SpeakeasyMetadata('form:name=name')]
    public string $name;
    
    /**
     * $photoUrls
     * 
     * @var array<string> $photoUrls
     */
	#[\JMS\Serializer\Annotation\SerializedName('photoUrls')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[SpeakeasyMetadata('form:name=photoUrls')]
    public array $photoUrls;
    
    /**
     * pet status in the store
     * 
     * @var ?\Testing\petstore\Models\Shared\PetStatus $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<Testing\petstore\Models\Shared\PetStatus>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=status')]
    public ?PetStatus $status = null;
    
    /**
     * $tags
     * 
     * @var ?array<\Testing\petstore\Models\Shared\Tag> $tags
     */
	#[\JMS\Serializer\Annotation\SerializedName('tags')]
    #[\JMS\Serializer\Annotation\Type('array<Testing\petstore\Models\Shared\Tag>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=tags,json=true')]
    public ?array $tags = null;
    
	public function __construct()
	{
		$this->category = null;
		$this->id = null;
		$this->name = "";
		$this->photoUrls = [];
		$this->status = null;
		$this->tags = null;
	}
}
