<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Testing\petstore;

/**
 * Petstore - Swagger Petstore - OpenAPI 3.0: This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
 * 
 * Swagger at [http://swagger.io](http://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
 * You can now help us improve the API whether it's by making changes to the definition itself or to the code.
 * That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
 * 
 * Some useful links:
 * - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
 * - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 * http://swagger.io - Find out more about Swagger
 * 
 * @package Testing\petstore
 * @access public
 * @see http://swagger.io
 */
class Petstore
{
	public const SERVERS = [
		'/api/v3',
	];
  	
    /**
     * Everything about your Pets
     * 
     * @var Pet $$pet
     */
	public Pet $pet;
	
    /**
     * Access to Petstore orders
     * 
     * @var Store $$store
     */
	public Store $store;
	
    /**
     * Operations about user
     * 
     * @var User $$user
     */
	public User $user;
		
	private SDKConfiguration $sdkConfiguration;

	/**
	 * Returns a new instance of the SDK builder used to configure and create the SDK instance.
	 * 
	 * @return PetstoreBuilder
	 */
	public static function builder(): PetstoreBuilder
	{
		return new PetstoreBuilder();
	}

	/**
	 * @param SDKConfiguration $sdkConfiguration
	 */
	public function __construct(SDKConfiguration $sdkConfiguration)
	{
		$this->sdkConfiguration = $sdkConfiguration;
		
		$this->pet = new Pet($this->sdkConfiguration);
		
		$this->store = new Store($this->sdkConfiguration);
		
		$this->user = new User($this->sdkConfiguration);
	}
}